defaults:
  - _self_
  - architecture: base

base_lr: 0.005
warmup_lr: 0.000005
warmup_epochs: 0
batch_size: 32
epochs: 1
patience: 4
clip_grad: 0.5
temperature: 0.1
log_interval: 10
save_top_k: 3
run_name: hydra-test-1
offline: true
